properties of numpy data structure

In [29]:
import numpy as np

In [30]:
x = np.array([[[2,3,4,5],[4,8,7,6]],[[1,0,5,7],[7,8,6,3]]])
print(x)

[[[2 3 4 5]
  [4 8 7 6]]

 [[1 0 5 7]
  [7 8 6 3]]]


In [31]:
#shape of ndarray
print(x.shape)

(2, 2, 4)


In [25]:
#dimension of the ndarray
print(x.ndim)

3


In [32]:
#print the size of the array
print(x.size)


16


In [33]:
#print the byte size
print(x.nbytes)

64


# Numpy constants

In [35]:
print(np.inf)
print(np.NAN)
print(np.NZERO)
print(np.NINF)
print(np.PZERO)
print(np.e)
print(np.euler_gamma)
print(np.pi)

inf
nan
-0.0
-inf
0.0
2.718281828459045
0.5772156649015329
3.141592653589793


In [38]:
print(x.T)

[[[2 1]
  [4 7]]

 [[3 0]
  [8 8]]

 [[4 5]
  [7 6]]

 [[5 7]
  [6 3]]]
