In [1]:
import numpy as np


In [9]:
# 1-D array

x = np.array([1,2,4,5])

print(x)

print(type(x))

[1 2 4 5]
<class 'numpy.ndarray'>


In [12]:
# we can acess element by its index
print(x[0]); print(x[1]); print(x[2]);

1
2
4


In [13]:
#last element
print(x[-1]);

5


In [17]:
#2-d array

y = np.array([[2,3,4,5],[5,2,4,1]],np.int16)
print(y)

[[2 3 4 5]
 [5 2 4 1]]


In [30]:
# we can acess element by its index
print(y[0][1]); print(y[0,2]); print(y[1,3]);

3
4
1


In [31]:
#slicing array
print(x[:,3])

[5 1]


In [32]:
#prints the 1st column
print(x[:,0])

[2 5]


In [33]:
#prints the 2nd column
print(x[:,1])

[3 2]


In [34]:
#prints the 3rd column
print(x[:,2])

[4 4]


In [35]:
#prints the 1st row
print(x[0,:])

[2 3 4 5]


In [36]:
#prints the 2nd row
print(x[1,:])

[5 2 4 1]


In [37]:
#3-d array

z = np.array([[[2,3,4,5],[5,2,4,1]],[[-1,2,3,6],[9,8,6,7]]],np.int16)
print(z)

[[[ 2  3  4  5]
  [ 5  2  4  1]]

 [[-1  2  3  6]
  [ 9  8  6  7]]]


In [40]:
# we can acess element by its index
print(z[0][0][0]); print(z[0,1,2]); print(z[1,1,0]);

2
4
9


In [42]:
#prints the 1st column
print(z[:,:,0])

[[ 2  5]
 [-1  9]]


In [43]:
#prints the 2nd column
print(z[:,:,1])

[[3 2]
 [2 8]]


In [45]:
#prints the 1st row for all the sub-arrays
print(z[:,0,:])

[[ 2  3  4  5]
 [-1  2  3  6]]


In [46]:
#prints the 1st row
print(z[0,:,:])

[[2 3 4 5]
 [5 2 4 1]]
